name: Bug Report
description: Report a bug in Suncode CLI
labels: ["bug", "pkg:cli"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Suncode Version
      description: Output of `suncode --version`
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Output of `node --version`
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
