"""CLI handlers for execution DAG planning and persistent scheduling."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from .config import get_execution_dag_settings
from .execution_context import ContextBuildError, read_node_context_manifest
from .execution_model import (
    ExecutionPlanError,
    execution_plan_to_dict,
    load_execution_plan,
    normalize_legacy_plan,
    topological_nodes,
    write_execution_plan,
)
from .execution_runtime import (
    ExecutionRuntimeError,
    cancel_execution_node,
    claim_execution_node,
    complete_execution_node,
    get_execution_status,
    get_ready_nodes,
    make_capabilities,
    mark_execution_node_running,
    recover_execution_run,
    start_execution_run,
)
from .paths import get_repo_root
from .task_utils import resolve_task_dir


def configure_execution_parser(parser: argparse.ArgumentParser) -> None:
    """Configure ``task.py execution`` nested subcommands."""
    actions = parser.add_subparsers(dest="execution_command", help="Execution DAG actions")

    validate = actions.add_parser("validate", help="Validate execution.json")
    validate.add_argument("dir", help="Task directory")
    validate.add_argument(
        "--allow-legacy",
        action="store_true",
        help="Normalize legacy artifacts when execution.json is absent",
    )
    validate.add_argument("--json", action="store_true", help="Output machine-readable JSON")

    show = actions.add_parser("show", help="Show normalized execution plan")
    show.add_argument("dir", help="Task directory")
    show.add_argument("--json", action="store_true", help="Output the normalized JSON plan")

    scaffold = actions.add_parser(
        "scaffold",
        help="Create a conservative serial execution.json from legacy artifacts",
    )
    scaffold.add_argument("dir", help="Task directory")
    scaffold.add_argument("--force", action="store_true", help="Replace an existing execution.json")

    start_run = actions.add_parser("start-run", help="Start a recoverable DAG execution run")
    start_run.add_argument("dir", help="Task directory")
    start_run.add_argument(
        "--executor",
        choices=("inline", "native-subagent", "channel"),
        default="inline",
        help="Executor capability kind",
    )
    start_run.add_argument(
        "--max-concurrency",
        type=int,
        help="Executor concurrency limit (defaults to execution.dag.max_concurrency)",
    )
    start_run.add_argument(
        "--roles",
        default="implement,check,fix,integration,research",
        help="Comma-separated supported node roles",
    )
    start_run.add_argument(
        "--isolation",
        choices=("shared-worktree", "worktree", "sandbox"),
        default="shared-worktree",
    )
    start_run.add_argument("--no-wait-any", action="store_true")
    start_run.add_argument("--supports-cancellation", action="store_true")
    start_run.add_argument("--no-clean-context", action="store_true")
    start_run.add_argument("--run-id", help="Stable run identifier (generated by default)")
    start_run.add_argument("--parent-session", help="Parent session identity for context isolation")
    start_run.add_argument("--json", action="store_true")

    ready = actions.add_parser("ready", help="Return the maximal safe fan-out set")
    _add_run_arguments(ready)

    claim = actions.add_parser("claim", help="Claim a ready node and build its context manifest")
    claim.add_argument("dir", help="Task directory")
    claim.add_argument("node", help="Node id")
    claim.add_argument("--run-id")
    claim.add_argument("--executor-ref", help="Adapter-specific worker/session reference")
    claim.add_argument("--json", action="store_true")

    running = actions.add_parser("running", help="Mark a dispatched node running")
    running.add_argument("dir", help="Task directory")
    running.add_argument("node", help="Node id")
    running.add_argument("--run-id")
    running.add_argument("--executor-ref")
    running.add_argument("--json", action="store_true")

    complete = actions.add_parser("complete", help="Record a structured NodeResult v1")
    complete.add_argument("dir", help="Task directory")
    complete.add_argument("node", help="Node id")
    complete.add_argument("--run-id")
    complete.add_argument("--result", required=True, help="NodeResult JSON path, or '-' for stdin")
    complete.add_argument("--json", action="store_true")

    status = actions.add_parser("status", help="Show execution runtime status")
    _add_run_arguments(status)

    recover = actions.add_parser(
        "recover",
        help="Reconcile results and explicitly handle confirmed-lost work",
    )
    recover.add_argument("dir", help="Task directory")
    recover.add_argument("--run-id")
    recover.add_argument(
        "--retry",
        action="append",
        default=[],
        metavar="NODE",
        help="Explicitly retry a failed, cancelled, or orphaned node",
    )
    recover.add_argument(
        "--force-orphan",
        action="append",
        default=[],
        metavar="NODE",
        help="Mark a confirmed-lost dispatched/running node orphaned",
    )
    recover.add_argument("--json", action="store_true")

    cancel = actions.add_parser("cancel", help="Cancel a non-terminal node")
    cancel.add_argument("dir", help="Task directory")
    cancel.add_argument("node", help="Node id")
    cancel.add_argument("--run-id")
    cancel.add_argument("--reason", default="cancelled by coordinator")
    cancel.add_argument("--json", action="store_true")

    context = actions.add_parser(
        "context",
        help="Verify and print an immutable node context manifest",
    )
    context.add_argument("manifest", help="Repo-relative or absolute manifest.json path")
    context.add_argument("--json", action="store_true")


def cmd_execution(args: argparse.Namespace) -> int:
    """Dispatch an execution DAG subcommand."""
    command = getattr(args, "execution_command", None)
    if command == "validate":
        return _cmd_validate(args)
    if command == "show":
        return _cmd_show(args)
    if command == "scaffold":
        return _cmd_scaffold(args)
    if command == "start-run":
        return _cmd_start_run(args)
    if command == "ready":
        return _cmd_ready(args)
    if command == "claim":
        return _cmd_claim(args)
    if command == "running":
        return _cmd_running(args)
    if command == "complete":
        return _cmd_complete(args)
    if command == "status":
        return _cmd_status(args)
    if command == "recover":
        return _cmd_recover(args)
    if command == "cancel":
        return _cmd_cancel(args)
    if command == "context":
        return _cmd_context(args)
    print("Error: execution action required; run 'task.py execution --help'", file=sys.stderr)
    return 2


def _add_run_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("dir", help="Task directory")
    parser.add_argument("--run-id")
    parser.add_argument("--json", action="store_true")


def _resolve_task_dir_or_error(task_ref: str) -> Path | None:
    repo_root = get_repo_root()
    task_dir = resolve_task_dir(task_ref, repo_root)
    if task_dir.is_dir():
        return task_dir
    print(f"Error: Task not found: {task_ref}", file=sys.stderr)
    return None


def _cmd_validate(args: argparse.Namespace) -> int:
    task_dir = _resolve_task_dir_or_error(args.dir)
    if task_dir is None:
        return 1
    try:
        plan = load_execution_plan(task_dir, allow_legacy=args.allow_legacy)
    except ExecutionPlanError as exc:
        if args.json:
            print(json.dumps({"valid": False, "error": str(exc)}, ensure_ascii=False))
        else:
            print(f"Error: {exc}", file=sys.stderr)
        return 1
    payload = {
        "valid": True,
        "source": plan.source,
        "planHash": plan.plan_hash,
        "nodeCount": len(plan.nodes),
        "topologicalOrder": [node.id for node in topological_nodes(plan)],
        "finalBarrier": list(plan.final_barrier),
    }
    if args.json:
        print(json.dumps(payload, ensure_ascii=False))
    else:
        print(f"✓ Execution plan valid ({len(plan.nodes)} nodes, source: {plan.source})")
        print(f"Plan hash: {plan.plan_hash}")
        print(f"Topological order: {' -> '.join(payload['topologicalOrder'])}")
    return 0


def _cmd_show(args: argparse.Namespace) -> int:
    task_dir = _resolve_task_dir_or_error(args.dir)
    if task_dir is None:
        return 1
    try:
        plan = load_execution_plan(task_dir, allow_legacy=True)
    except ExecutionPlanError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    if args.json:
        print(json.dumps(execution_plan_to_dict(plan), indent=2, ensure_ascii=False))
        return 0
    print(f"Execution plan: {plan.task} ({plan.source}, {len(plan.nodes)} nodes)")
    print(f"Plan hash: {plan.plan_hash}")
    for node in topological_nodes(plan):
        dependencies = ", ".join(node.depends_on) if node.depends_on else "-"
        print(f"- [{node.priority}] {node.id} ({node.role}); depends on: {dependencies}")
    print(f"Final barrier: {', '.join(plan.final_barrier)}")
    return 0


def _cmd_scaffold(args: argparse.Namespace) -> int:
    task_dir = _resolve_task_dir_or_error(args.dir)
    if task_dir is None:
        return 1
    target = task_dir / "execution.json"
    if target.exists() and not args.force:
        print(f"Error: {target} already exists; pass --force to replace it", file=sys.stderr)
        return 1
    try:
        plan = normalize_legacy_plan(task_dir)
        write_execution_plan(task_dir, plan)
    except (ExecutionPlanError, OSError) as exc:
        print(f"Error: could not scaffold execution.json: {exc}", file=sys.stderr)
        return 1
    print(f"✓ Created {target}")
    print("Review dependencies, read/write scopes, resources, validation, and final barrier before dispatch.")
    return 0


def _cmd_start_run(args: argparse.Namespace) -> int:
    task_dir = _resolve_task_dir_or_error(args.dir)
    if task_dir is None:
        return 1
    settings = get_execution_dag_settings(get_repo_root())
    if not settings.enabled:
        return _runtime_error(
            ExecutionRuntimeError(
                "execution DAG is disabled by execution.dag.enabled; use the legacy serial workflow or enable it"
            ),
            args.json,
        )
    try:
        roles = tuple(role.strip() for role in args.roles.split(",") if role.strip())
        capabilities = make_capabilities(
            kind=args.executor,
            max_concurrency=(
                args.max_concurrency
                if args.max_concurrency is not None
                else settings.max_concurrency
            ),
            roles=roles,
            supports_wait_any=not args.no_wait_any,
            supports_cancellation=args.supports_cancellation,
            supports_clean_context=not args.no_clean_context,
            isolation=args.isolation,
        )
        run_dir, state = start_execution_run(
            repo_root=get_repo_root(),
            task_dir=task_dir,
            capabilities=capabilities,
            run_id=args.run_id,
            parent_session=args.parent_session,
        )
    except (ExecutionPlanError, ExecutionRuntimeError) as exc:
        return _runtime_error(exc, args.json)
    payload = {
        "runId": state["runId"],
        "status": state["status"],
        "planHash": state["planHash"],
        "runtimePath": str(run_dir),
        "executor": state["executor"],
        "warnings": state["warnings"],
    }
    return _runtime_output(payload, args.json, f"✓ Started execution run {state['runId']}")


def _cmd_ready(args: argparse.Namespace) -> int:
    task_dir = _resolve_task_dir_or_error(args.dir)
    if task_dir is None:
        return 1
    try:
        _, state, nodes = get_ready_nodes(
            repo_root=get_repo_root(),
            task_dir=task_dir,
            run_id=args.run_id,
        )
    except ExecutionRuntimeError as exc:
        return _runtime_error(exc, args.json)
    payload = {
        "runId": state["runId"],
        "status": state["status"],
        "fanOutBeforeWait": True,
        "selected": [
            {
                "id": node.id,
                "role": node.role,
                "priority": node.priority,
                "dependsOn": list(node.depends_on),
            }
            for node in nodes
        ],
        "active": [
            node_id
            for node_id, node_state in state["nodes"].items()
            if node_state["status"] in ("dispatched", "running")
        ],
    }
    return _runtime_output(
        payload,
        args.json,
        "Ready fan-out: " + (", ".join(node.id for node in nodes) or "none"),
    )


def _cmd_claim(args: argparse.Namespace) -> int:
    task_dir = _resolve_task_dir_or_error(args.dir)
    if task_dir is None:
        return 1
    try:
        _, state, dispatch = claim_execution_node(
            repo_root=get_repo_root(),
            task_dir=task_dir,
            node_id=args.node,
            run_id=args.run_id,
            executor_ref=args.executor_ref,
        )
    except ExecutionRuntimeError as exc:
        return _runtime_error(exc, args.json)
    payload = {"status": state["status"], "dispatch": dispatch}
    return _runtime_output(payload, args.json, f"✓ Claimed {args.node}")


def _cmd_running(args: argparse.Namespace) -> int:
    task_dir = _resolve_task_dir_or_error(args.dir)
    if task_dir is None:
        return 1
    try:
        _, state = mark_execution_node_running(
            repo_root=get_repo_root(),
            task_dir=task_dir,
            node_id=args.node,
            run_id=args.run_id,
            executor_ref=args.executor_ref,
        )
    except ExecutionRuntimeError as exc:
        return _runtime_error(exc, args.json)
    return _runtime_output(
        {"runId": state["runId"], "node": args.node, "status": "running"},
        args.json,
        f"✓ {args.node} is running",
    )


def _cmd_complete(args: argparse.Namespace) -> int:
    task_dir = _resolve_task_dir_or_error(args.dir)
    if task_dir is None:
        return 1
    try:
        result = _read_result_argument(args.result)
        _, state, stored = complete_execution_node(
            repo_root=get_repo_root(),
            task_dir=task_dir,
            node_id=args.node,
            result_value=result,
            run_id=args.run_id,
        )
    except (ExecutionRuntimeError, OSError, json.JSONDecodeError) as exc:
        return _runtime_error(exc, args.json)
    payload = {
        "runId": state["runId"],
        "node": args.node,
        "nodeStatus": state["nodes"][args.node]["status"],
        "runStatus": state["status"],
        "result": stored,
    }
    return _runtime_output(payload, args.json, f"✓ Recorded result for {args.node}")


def _cmd_status(args: argparse.Namespace) -> int:
    task_dir = _resolve_task_dir_or_error(args.dir)
    if task_dir is None:
        return 1
    try:
        run_dir, state = get_execution_status(
            repo_root=get_repo_root(),
            task_dir=task_dir,
            run_id=args.run_id,
        )
    except ExecutionRuntimeError as exc:
        return _runtime_error(exc, args.json)
    payload = {**state, "runtimePath": str(run_dir)}
    if args.json:
        print(json.dumps(payload, ensure_ascii=False))
    else:
        print(f"Execution run {state['runId']}: {state['status']}")
        for node_id, node_state in state["nodes"].items():
            print(f"- {node_id}: {node_state['status']} (attempt {node_state['attempt']})")
    return 0


def _cmd_recover(args: argparse.Namespace) -> int:
    task_dir = _resolve_task_dir_or_error(args.dir)
    if task_dir is None:
        return 1
    try:
        _, state, actions = recover_execution_run(
            repo_root=get_repo_root(),
            task_dir=task_dir,
            run_id=args.run_id,
            retry_nodes=tuple(args.retry),
            force_orphan_nodes=tuple(args.force_orphan),
        )
    except ExecutionRuntimeError as exc:
        return _runtime_error(exc, args.json)
    payload = {"runId": state["runId"], "status": state["status"], "actions": actions}
    return _runtime_output(payload, args.json, "Recovery: " + ("; ".join(actions) or "no changes"))


def _cmd_cancel(args: argparse.Namespace) -> int:
    task_dir = _resolve_task_dir_or_error(args.dir)
    if task_dir is None:
        return 1
    try:
        _, state = cancel_execution_node(
            repo_root=get_repo_root(),
            task_dir=task_dir,
            node_id=args.node,
            run_id=args.run_id,
            reason=args.reason,
        )
    except ExecutionRuntimeError as exc:
        return _runtime_error(exc, args.json)
    return _runtime_output(
        {"runId": state["runId"], "node": args.node, "status": "cancelled"},
        args.json,
        f"✓ Cancelled {args.node}",
    )


def _cmd_context(args: argparse.Namespace) -> int:
    try:
        manifest, content = read_node_context_manifest(
            get_repo_root(),
            args.manifest,
        )
    except ContextBuildError as exc:
        return _runtime_error(exc, args.json)
    if args.json:
        print(
            json.dumps(
                {"manifest": manifest, "content": content},
                ensure_ascii=False,
            )
        )
    else:
        print(content, end="" if content.endswith("\n") else "\n")
    return 0


def _read_result_argument(value: str) -> object:
    if value == "-":
        return json.loads(sys.stdin.read())
    return json.loads(Path(value).read_text(encoding="utf-8"))


def _runtime_error(error: BaseException, as_json: bool) -> int:
    if as_json:
        print(json.dumps({"ok": False, "error": str(error)}, ensure_ascii=False))
    else:
        print(f"Error: {error}", file=sys.stderr)
    return 1


def _runtime_output(payload: dict[str, object], as_json: bool, message: str) -> int:
    if as_json:
        print(json.dumps(payload, ensure_ascii=False))
    else:
        print(message)
    return 0
