/**
 * Template hash utilities for detecting user modifications
 *
 * Stores SHA256 hashes of template files at install time.
 * Used to determine if users have modified templates.
 *
 * Cross-platform contract:
 * - All hash dictionary keys are POSIX style (`/`), never `\`.
 * - Hashes are computed against LF-normalized content, so CRLF and LF
 *   versions of the same logical content produce the same hash.
 * - Persisted JSON uses schema `{ __version: 2, hashes: { ... } }`. Old
 *   flat-format files (no `__version`) are silently discarded; the hash
 *   set is regenerated on next init/update.
 */

import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";

import { DIR_NAMES, FILE_NAMES } from "../constants/paths.js";
import type { TemplateHashes } from "../types/migration.js";
import { toPosix } from "./posix.js";

/** File name for storing template hashes */
const HASHES_FILE = ".template-hashes.json";

/** Current schema version for `.template-hashes.json` */
const HASHES_SCHEMA_VERSION = 2;

/** Persisted shape of the hashes file (v2). */
interface StoredHashesV2 {
  __version: number;
  hashes: TemplateHashes;
}

/**
 * Compute SHA256 hash of content.
 *
 * Normalizes line endings (CRLF -> LF) before hashing so that the same
 * logical content yields the same hash across platforms.
 */
export function computeHash(content: string): string {
  const normalized = content.replace(/\r\n/g, "\n");
  return createHash("sha256").update(normalized, "utf-8").digest("hex");
}

/**
 * Get path to the hashes file
 */
function getHashesPath(cwd: string): string {
  return path.join(cwd, DIR_NAMES.WORKFLOW, HASHES_FILE);
}

/**
 * Normalize all keys of a hashes record to POSIX form.
 */
function normalizeHashKeys(hashes: TemplateHashes): TemplateHashes {
  const out: TemplateHashes = {};
  for (const [key, value] of Object.entries(hashes)) {
    out[toPosix(key)] = value;
  }
  return out;
}

/**
 * Load stored template hashes.
 *
 * Returns `{}` for: missing file, invalid JSON, or legacy flat-format
 * files (no `__version`). Legacy files are silently dropped; the hash
 * set is regenerated by subsequent init/update logic. This handles two
 * Windows compatibility issues at once: backslash keys and CRLF-based
 * hashes both differ from the v2 contract.
 */
export function loadHashes(cwd: string): TemplateHashes {
  const hashesPath = getHashesPath(cwd);
  if (!fs.existsSync(hashesPath)) {
    return {};
  }

  try {
    const content = fs.readFileSync(hashesPath, "utf-8");
    const parsed = JSON.parse(content) as unknown;

    if (
      parsed !== null &&
      typeof parsed === "object" &&
      "__version" in parsed &&
      (parsed as { __version: unknown }).__version === HASHES_SCHEMA_VERSION &&
      "hashes" in parsed &&
      typeof (parsed as { hashes: unknown }).hashes === "object" &&
      (parsed as { hashes: unknown }).hashes !== null
    ) {
      const stored = parsed as StoredHashesV2;
      // Defensive: enforce POSIX keys even if a writer slipped through.
      return normalizeHashKeys(stored.hashes);
    }

    // Legacy flat format (no __version) or unknown shape: discard.
    return {};
  } catch {
    return {};
  }
}

/**
 * Save template hashes.
 *
 * Always writes the v2 schema with POSIX-normalized keys.
 */
export function saveHashes(cwd: string, hashes: TemplateHashes): void {
  const hashesPath = getHashesPath(cwd);
  const payload: StoredHashesV2 = {
    __version: HASHES_SCHEMA_VERSION,
    hashes: normalizeHashKeys(hashes),
  };
  fs.writeFileSync(hashesPath, JSON.stringify(payload, null, 2));
}

/**
 * Update hashes for specific files
 *
 * @param cwd - Working directory
 * @param files - Map of relative paths to file contents
 */
export function updateHashes(cwd: string, files: Map<string, string>): void {
  const hashes = loadHashes(cwd);

  for (const [relativePath, content] of files) {
    hashes[toPosix(relativePath)] = computeHash(content);
  }

  saveHashes(cwd, hashes);
}

/**
 * Update hash for a single file by reading its current content
 */
export function updateHashFromFile(cwd: string, relativePath: string): void {
  const fullPath = path.join(cwd, relativePath);
  if (!fs.existsSync(fullPath)) {
    return;
  }

  const content = fs.readFileSync(fullPath, "utf-8");
  const hashes = loadHashes(cwd);
  hashes[toPosix(relativePath)] = computeHash(content);
  saveHashes(cwd, hashes);
}

/**
 * Remove hash entry for a file (e.g., after deletion)
 */
export function removeHash(cwd: string, relativePath: string): void {
  const hashes = loadHashes(cwd);
  const key = toPosix(relativePath);
  const { [key]: _, ...rest } = hashes;
  saveHashes(cwd, rest);
}

/**
 * Rename hash entry (used after file rename)
 */
export function renameHash(
  cwd: string,
  oldPath: string,
  newPath: string,
): void {
  const hashes = loadHashes(cwd);
  const oldKey = toPosix(oldPath);
  const newKey = toPosix(newPath);
  if (hashes[oldKey]) {
    const { [oldKey]: oldValue, ...rest } = hashes;
    rest[newKey] = oldValue;
    saveHashes(cwd, rest);
  }
}

/**
 * Check if a template file has been modified by the user
 *
 * @param cwd - Working directory
 * @param relativePath - Relative path to the file
 * @param hashes - Stored template hashes
 * @returns true if file has been modified from template, false otherwise
 */
export function isTemplateModified(
  cwd: string,
  relativePath: string,
  hashes: TemplateHashes,
): boolean {
  const fullPath = path.join(cwd, relativePath);

  // If file doesn't exist, can't be modified
  if (!fs.existsSync(fullPath)) {
    return false;
  }

  // If we don't have a stored hash, assume it's modified (conservative).
  // Lookup by POSIX key — hashes loaded via loadHashes are already
  // normalized, but the caller may have built `hashes` themselves.
  const posixKey = toPosix(relativePath);
  const storedHash = hashes[posixKey] ?? hashes[relativePath];
  if (!storedHash) {
    return true;
  }

  // Compare current content hash with stored hash
  const currentContent = fs.readFileSync(fullPath, "utf-8");
  const currentHash = computeHash(currentContent);

  return currentHash !== storedHash;
}

/**
 * Check if a file matches its original template content
 * (Useful for determining if a file can be safely auto-migrated)
 *
 * @param cwd - Working directory
 * @param relativePath - Relative path to the file
 * @param originalContent - Original template content
 * @returns true if file matches original template
 */
export function matchesOriginalTemplate(
  cwd: string,
  relativePath: string,
  originalContent: string,
): boolean {
  const fullPath = path.join(cwd, relativePath);

  if (!fs.existsSync(fullPath)) {
    return false;
  }

  const currentContent = fs.readFileSync(fullPath, "utf-8");
  return currentContent === originalContent;
}

/**
 * Get modification status for multiple files
 *
 * @param cwd - Working directory
 * @param relativePaths - Array of relative paths to check
 * @param hashes - Stored template hashes
 * @returns Map of path to modification status
 */
export function getModificationStatus(
  cwd: string,
  relativePaths: string[],
  hashes: TemplateHashes,
): Map<string, boolean> {
  const result = new Map<string, boolean>();

  for (const relativePath of relativePaths) {
    result.set(relativePath, isTemplateModified(cwd, relativePath, hashes));
  }

  return result;
}

/**
 * Patterns to exclude from hash tracking (only applied to the .trellis/ walk).
 */
const EXCLUDE_FROM_HASH = [
  ".template-hashes.json", // Hash file itself
  ".version", // Version file
  ".gitignore", // Git ignore files
  ".developer", // Developer identity file
  "workspace/", // Workspace files (user data)
  "tasks/", // Task files (user data)
  ".current-task", // Current task marker (file, not directory)
  ".trellis/spec/", // User-customized spec files
  ".backup-", // Backup directories
];

/**
 * Check if a path should be excluded from hash tracking
 */
function shouldExcludeFromHash(relativePath: string): boolean {
  const normalizedPath = toPosix(relativePath);
  for (const pattern of EXCLUDE_FROM_HASH) {
    if (normalizedPath.includes(pattern)) {
      return true;
    }
  }
  return false;
}

/**
 * Recursively collect all files in a directory.
 *
 * Returned paths are POSIX-normalized so they can be used directly as
 * hash dictionary keys regardless of host OS.
 */
function collectFiles(cwd: string, dir: string): string[] {
  const fullDir = path.join(cwd, dir);
  if (!fs.existsSync(fullDir)) {
    return [];
  }

  const files: string[] = [];
  const entries = fs.readdirSync(fullDir, { withFileTypes: true });

  for (const entry of entries) {
    const relativePath = path.join(dir, entry.name);

    if (shouldExcludeFromHash(relativePath)) {
      continue;
    }

    if (entry.isDirectory()) {
      files.push(...collectFiles(cwd, relativePath));
    } else if (entry.isFile()) {
      files.push(toPosix(relativePath));
    }
  }

  return files;
}

/** Options accepted by {@link initializeHashes}. */
export interface InitializeHashesOptions {
  /**
   * POSIX-style relative paths trellis actually wrote during the init run
   * (captured via `startRecordingWrites` in `file-writer.ts`). Only these
   * paths are hashed for the platform/root-level coverage; anything else
   * under `.codex/` / `.claude/` / etc. is left alone, even if it exists
   * on disk. Setting this to `undefined` or an empty set means "no
   * platform/root coverage this run" — historical hashes from earlier
   * runs are preserved via `merge`.
   */
  trackedPaths?: ReadonlySet<string>;
  /**
   * When true, merge `trackedPaths`-derived hashes into the EXISTING manifest
   * instead of replacing it. Used by `handleReinit` "add platform" flow so
   * previously-tracked platforms aren't wiped from the manifest when only
   * a new platform's writes are recorded. Defaults to false (replace).
   */
  merge?: boolean;
}

/**
 * Initialize template hashes after init
 *
 * The platform/root section of the manifest comes from `trackedPaths` —
 * the set of POSIX paths that `writeFile` actually wrote (or owned with
 * byte-identical content) during this init run. Avoids the historical bug
 * where a blind directory walk of `.codex/` / `.claude/` swept up
 * user-owned runtime data (chat history, session JSONLs).
 *
 * `.trellis/` is still walked recursively (with `EXCLUDE_FROM_HASH`) because
 * uninstall removes `.trellis/` wholesale via `rm -rf` regardless of manifest
 * content — accuracy there doesn't affect data-loss, only `suncode update`
 * 3-way-merge fidelity (preserved by the existing walk).
 *
 * @returns Number of files hashed in the final manifest.
 */
export function initializeHashes(
  cwd: string,
  options: InitializeHashesOptions = {},
): number {
  const { trackedPaths, merge = false } = options;
  const hashes: TemplateHashes = merge ? loadHashes(cwd) : {};

  // Platform + root files: hash only paths actually written this run.
  if (trackedPaths) {
    for (const relativePath of trackedPaths) {
      // `.trellis/` paths are handled by the walk below — don't double-track.
      if (relativePath.startsWith(".trellis/") || relativePath === ".trellis") {
        continue;
      }
      const fullPath = path.join(cwd, ...relativePath.split("/"));
      if (!fs.existsSync(fullPath)) continue;
      try {
        const content = fs.readFileSync(fullPath, "utf-8");
        hashes[toPosix(relativePath)] = computeHash(content);
      } catch {
        // Skip files that can't be read (binary, etc.)
      }
    }
  }

  // .trellis/ workflow tree: still walked recursively. Accuracy here is for
  // `suncode update`'s 3-way merge of workflow.md / config.yaml / scripts;
  // uninstall removes .trellis/ wholesale so it does not matter for the
  // data-loss bug this contract addresses.
  const files = collectFiles(cwd, ".trellis");
  for (const relativePath of files) {
    const fullPath = path.join(cwd, relativePath);
    try {
      const content = fs.readFileSync(fullPath, "utf-8");
      hashes[relativePath] = computeHash(content);
    } catch {
      // Skip files that can't be read (binary, etc.)
    }
  }

  // Backwards-compat path: when `trackedPaths` is not supplied (callers that
  // haven't been updated yet), keep tracking root-level files that exist on
  // disk. This preserves the legacy behavior for tests / scripts that don't
  // go through the new recording flow.
  if (!trackedPaths) {
    for (const relativePath of [FILE_NAMES.AGENTS]) {
      if (shouldExcludeFromHash(relativePath)) continue;
      const fullPath = path.join(cwd, relativePath);
      if (!fs.existsSync(fullPath)) continue;
      try {
        const content = fs.readFileSync(fullPath, "utf-8");
        hashes[toPosix(relativePath)] = computeHash(content);
      } catch {
        // Skip
      }
    }
  }

  saveHashes(cwd, hashes);
  return Object.keys(hashes).length;
}
